# Add the core component that are required.
# Available core components:
# adc clkconfig gpio i2c ssp timer uart
CORE = gpio timer uart 

# Add modules from the modules folder that you want to use.
# Available modules:
# dac display encoder knob midi segment
# There's no module used by this example.
MODULES = 

# Update the following variable to your project structure.
BUILD_DIR = ../../build
SDK_DIR = ../..
SRC_DIR = .
FILENAME = blinky

LINKER_SCRIPT = lpc1114.ld

include $(SDK_DIR)/sdk.mk
